LIKE_CLAUSES = [
    'like',
    'like to',
    'love',
    'adore',
    'enjoy',
    'appreciate',
    'am a fond of',
    'am a fan of',
    'am a big fan of',
    'am a huge fan of',
    'am interested in',
    'i\'m a fond of',
    'i\'m  a fan of',
    'i\'m  a big fan of',
    'i\'m  a huge fan of',
    'i\'m  interested in'
]

DISLIKE_CLAUSES = [
    'dislike',
    'hate',
    'despise',
    'detest',
    'resent',
    'am turned off to',
    'i\'m turned off to',
    'do not appreciate',
    'don\'t like',
    'don\'t appreciate'
]

YES = [
    "yes",
    "all right",
    "very well",
    "of course",
    "by all means",
    "sure",
    "certainly",
    "absolutely",
    "indeed",
    "right",
    "affirmative",
    "in the affirmative",
    "agreed",
    "roger",
    "aye aye",
    "yeah",
    "yep",
    "yup",
    "ya",
    "uh-huh",
    "okay",
    "ok",
    "okey-dokey",
    "okey-doke",
    "yea",
    "aye",
    "course"
]

NO = [
    "no",
    "absolutely not",
    "most certainly not",
    "of course not",
    "under no circumstances",
    "by no means",
    "not at all",
    "negative",
    "never",
    "not really",
    "nope",
    "uh-uh",
    "nah",
    "not on your life",
    "no way",
    "ixnay",
    "nay"
]